config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'vacations/top' => 'vacations#top'
  resources :vacations
  get 'sindans/index' => 'sindans#index'
  root 'vacations#top'
  post '/sindans/index', to: 'sindans#index'
  patch 'vacations/:id' => 'vacations#update'
  delete 'vacations/:id' => 'vacations#destroy' 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :vacations 
 end

app/models/vacation.rb
class Vacation < ApplicationRecord
    belongs_to :user
    mount_uploader :image, ImageUploader
    attribute :body, :text
    validates :review, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sindans_controller.rb
class SindansController < ApplicationController
    def index 
    end
end

app/controllers/vacations_controller.rb
class VacationsController < ApplicationController
    before_action :authenticate_user!, only: [:new, :create]
    def top
      
    end
    def index
      @vacations = Vacation.all
    search = params[:search]
    @vacations = @vacations.joins(:user).where("name LIKE ?", "%#{search}%") if search.present?
    @vacations = @vacations.page(params[:page]).per(8)
    end
       
    
    
      def new
        @vacation = Vacation.new
      end
    
      def create
        @vacation = Vacation.new(vacation_params)
        @vacation.user_id = current_user.id
      
        # もし画像がアップロードされていない場合
        if params[:vacation][:image].blank?
          # デフォルト画像のパスを指定
          vacation.image = ActionController::Base.helpers.asset_path('default_image.jpg')
        end
      
        if @vacation.save
          redirect_to vacations_path, notice: '投稿が成功しました。'
        else
          render :new
        end
      end
    
      def show
        @vacation = Vacation.find(params[:id])
      end
    
      def edit
        @vacation = Vacation.find(params[:id])
      end
    
      def update
        vacation = Vacation.find(params[:id])
        if vacation.update(vacation_params)
          redirect_to :action => "show", :id => vacation.id
        else
          redirect_to :action => "new"
        end
      end
    
      
      def destroy
        vacation = Vacation.find(params[:id])
        vacation.destroy
        redirect_to action: :index
      end
    
    
      private
      def vacation_params
        params.require(:vacation).permit(:name, :date, :price, :place, :people, :image, :other_attributes, :overall, :review)
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sindans_helper.rb
module SindansHelper
end

app/helpers/vacations_helper.rb
module VacationsHelper
    def getPercent(number) 
        if number.present?
          calPercent = number/5.to_f * 100
          # calPercent = number/10.to_f * 100
          #↑１０段階評価の際は2行目コメントアウトを外して、1行目をコメントアウト。
          percent = calPercent.round
          #↑CSSは小数が含まれると、widthの幅を指定できないので四捨五入して整数化。
          return percent.to_s
        else
          return 0
        end
    end
  end

app/views/layouts/application.html.erb
<html>
  <head>
    <title>Asobi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  <header>
  <h1>遊び診断</h1>
  <div class="header-list">
  <ul>
   <li> <%= link_to "トップページ", vacations_top_path %> <li>
   <li> <%= link_to "遊び一覧", vacations_path %> <li>
   <li> <%= link_to "遊び診断", sindans_index_path %> <li>
  </ul>
  </div>
</header>
  <a href="https://front.codes/" class="logo" target="_blank">
  </a>
    <input class="menu-icon" type="checkbox" id="menu-icon" name="menu-icon"/>
    <label for="menu-icon"></label>
    <nav class="nav">
      <ul class="pt-5">
          <% if user_signed_in? %>
            <li><%= button_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
            <li> <%= link_to "トップページ", vacations_top_path %> <li>
            <li> <%= link_to "遊び投稿", new_vacation_path %> <li>
            <li> <%= link_to "遊び一覧", vacations_path %> <li>
            <li> <%= link_to "遊び診断", sindans_index_path %> <li>
          <% else %>
            <li><%= link_to "新規登録", new_user_registration_path %></li>
            <li><%= link_to "ログイン", new_user_session_path %></li>
          <% end %>
        </ul>
      </nav>
 <main>
  <%= yield %>
 </main>
</body>

</html>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/vacations/index.html.erb

<div class='search_box'>
  <h1>投稿を検索</h1>
  <div class='serch-form'>
  <%= form_tag({controller:"vacations",action:"index"}, method: :get) do %>
    <%= text_field_tag :search %>
    <%= submit_tag '検索する'  %>
  <% end %>
  </div>

  <div class='new_to_vacation'>
  <a href="<%= new_vacation_path %>" class="button2">新規に投稿する</a>
  </div>
</div>

<div class="vacations-container">

  <% @vacations.each do |t| %>
    <div class='vacations-container1'>
      <div class="vacation0">
        <div class='vacation1'>
          <%= image_tag t.image_url, size: "450x300" if t.image? %>
        </div>
        <div class='vacation2'><%= t.name %></div>     
        <div class='vacation4'><%= link_to "詳細へ", vacation_path(t.id) %></div>
        <div class='vacation5'><%= link_to "編集する", edit_vacation_path(t.id) %></div>
        <div class='vacation6'><%= button_to "削除する", vacation_path(t.id), method: :delete %></div>
      <div>
      <div class='vacation7'>
        <h2>総合評価：
          <span class="star-rating">
            <span class="star-rating-front" style="width: <%= getPercent(t.overall) %>%;">★★★★★</span>
            <span class="star-rating-back">★★★★★</span>
          </span> 
        </h2>
        </div>
        </div>
      </div>
    </div>
  <% end %>
    

</div>

<div class='index_under'>
  <%= page_entries_info @vacations %>
  <%= paginate @vacations %>
</div>

app/views/vacations/new.html.erb
<div class='new_asobi'>
  <div class='new_asobi_head'>新規投稿</div>
  <div class='new_asobi_body'>
    <%= form_for @vacation do |f| %>

    遊びの名前
      <div class="field">
        <%= f.label :name %>
        <%= f.text_field :name, :size => 30 %>
      
        
    </div>


    日数
      <div class="field">
        <%= f.label :date %>
        <%= f.select :date, 
        [["半日以下", "半日以下"], 
        ["１日", "１日"], 
        ["２日以上", "２日以上"]], include_blank: "選択して下さい" %>
      </div>

    １人あたりの価格
      <div class="field">
        <%= f.label :price  %>
        <%= f.number_field :price, :size => 10 %>
      </div>

    場所
      <div class="field">
        <%= f.label :place  %>
        <%= f.text_area :place, :size => "30x2" %>
      </div>
      <div class="field">
        <%= f.label :review %>
        <%= f.text_area :review, rows: 4 %>
      </div>
      <div class="field">
        <%= f.label :image %>
        <%= f.file_field :image %>
      </div>
    総合評価
        <div class="post_form">
            <%= f.radio_button :overall, 5 ,id: 'star1'%>
            <label for="star1"><span class="text">最高</span>★</label>
        
            <%= f.radio_button :overall, 4 ,id: 'star2'%>
            <label for="star2"><span class="text">良い</span>★</label>
        
            <%= f.radio_button :overall, 3 ,id: 'star3'%>
            <label for="star3"><span class="text">普通</span>★</label>
        
            <%= f.radio_button :overall, 2 ,id: 'star4'%>
            <label for="star4"><span class="text">悪い</span>★</label>
        
            <%= f.radio_button :overall, 1 ,id: 'star5'%>
            <label for="star5"><span class="text">最悪</span>★</label>
        </div>

      <%= f.submit "投稿する" %>
    <% end %>
 </div>
  <%= link_to "一覧に戻る", vacations_path %>
</div>

app/views/vacations/show.html.erb
<div class='show_all'>

    <div class=show_head>
        遊びの詳細
    </div>

    <div class="show_body">

        <div class='show_a'>
            <div class='show_body1'><%= @vacation.name %></div>
            <div class='show_body2'>
            <%= image_tag @vacation.image_url, size: "600x400" if @vacation.image? %></div>
        </div>

        <div class='show_b'>
            <div class='show_body3'>・場所...<%= @vacation.place %></div>
            <div class='show_body4'>・値段...<%= @vacation.price %></div>
            <div class='show_body5'>・日数...<%= @vacation.date %></div>
            <div class='show_body6'>・感想...<%= @vacation.review %></div>
         </div>

    </div>

    <div class=show_foot>
      <%= link_to "遊び一覧に戻る", vacations_path %>
    </div>

</div>

app/views/vacations/top.html.erb
<div class='top'>
  <div class='asobi_block1'>
     <div class='asobi_block2'>Play Now</div>
  </div>

  

   <div class='sindan_block2'>
   <div class='sindan_block21'></div>
   <div class='sindan_block22'></div>
   <div class='sindan_block23'></div>
   </div>

  

   <div class='sindan_block4'>
      
      <div class='sindan_block41'>
      ~遊び診断について~
      </div>

      <div class='sindan_block5_1'>
         <div class='sindan_block5'>
            <div class='sindan_block5_image'>
               <%= image_tag 'rupe.jpg' %>
            </div>
         </div>
        
         <div class='sindan_block42'>
            <div =class='sindan_block42_top1'>
            診断
            </div>
            <div =class='sindan_block42_body1'>
            複数の選択肢からあなたにピッタリの遊びを診断します！
            迷ったらとりあえず診断するのがおススメ！
            </div>
         </div>
       
     </div>

     <div class='sindan_block5_1'>
         <div class='sindan_block5'>
            <div class='sindan_block5_image'>
               <%= image_tag 'list.jpg' %>
            </div>
         </div>
        
           <div class='sindan_block42'>
               <div =class='sindan_block42_top1'>
               一覧
               </div>
               <div =class='sindan_block42_body1'>
               みんなが投稿したものを一覧で表示してます！
               どんな遊びがあるのか、あなたにピンとくるものがあるかも？
               </div>
            </div>
       
     </div>

     <div class='sindan_block5_1'>
         <div class='sindan_block5'>
            <div class='sindan_block5_image'>
               <%= image_tag 'kawaii.jpg' %>
            </div>
         </div>
        
           <div class='sindan_block42'>
               <div =class='sindan_block42_top1'>
               詳細
               </div>
               <div =class='sindan_block42_body1'>
               一覧ページで表示されている遊びの詳細が確認できます！
               他の人のプランを覗いてみましょう！

               </div>
            </div>
        
     </div>
     
   </div>
   
    
   <div class='sindan_block1'>
      <div class="anime-box">

            <div class='sindan_block_a'> <p class="TextAnime">今あなたはどんな遊びがしたいですか？</p></div>
            <div class='sindan_block_b'><p class="TextAnime">どうしよう、、、、</p><div>
            <div class='sindan_block_c'><p class="TextAnime"> いい遊びが思いつかない、、</p><div>
            <div class='sindan_block_d'><p class="TextAnime">そんなあなたに！</p> <div>
            <div class='sindan_block_e'><p class="TextAnime">いまぴったりの遊びをご紹介します！</p> <div>
       </div>
 </div>
 <div class='sindan_block3'>
     <a href="<%= sindans_index_path %>" class="button1">診断を始める</a>
   </div>
</div>